# 1. write a program to create a 5 dimensional array with all zeros and ones

In [2]:
import numpy as np

In [143]:
x1=np.zeros((5,5),dtype=int)

In [145]:
y=np.array(x1,ndmin=5)

In [146]:
y

array([[[[[0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0]]]]])

In [147]:
x2=np.ones((5,5),dtype=int)
y1=np.array(x2,ndmin=5)

In [148]:
y1

array([[[[[1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1]]]]])

# 2.write a program to create an array of 10 zeros,10 ones, and 10 fives in row 1 2 and 3 which create a new array of shape (3,10)

In [149]:
x=np.zeros(10,)
x1=np.ones(10,)
x2=np.ones(10,)*5

In [153]:
y=np.array((x,x1,x2),dtype=int).reshape(3,10)

In [154]:
y

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]])

# 3. write a program to create a 3*4 matrix filled with values from 10 to 21

In [62]:
np.arange(10,22).reshape(3,4)

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

# 4. write a program to create a 10*10 zero matrix with elements on the main diagnol equal to 0,1,2,3,4,5,6,7,8,9,

In [63]:
np.diag([0,1,2,3,4,5,6,7,8,9])

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 9]])

# 5. write a program to create a 4*4 array. create an array from below array by swapping first and last, second and third columns.

In [65]:
x=np.arange(1,17).reshape(4,4)

In [66]:
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [80]:
x[:,::-1]

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9],
       [16, 15, 14, 13]])

# 6. write a program to reverse an array(the first element becomes the last).Given array: [12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27]

In [81]:
x=np.array([12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27])

In [82]:
x

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [84]:
x[::-1]

array([27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12])

# 7. write a program to access all the elements greater than 30 and less than 80 and multiples of 5 from an array of shape 10, 10 elements range from 1 to 100

In [86]:
x= np.arange(1,101).reshape(10,10)

In [87]:
x

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [97]:
y=(x>30) & (x<80)

In [98]:
y

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [100]:
z=x[y]

In [101]:
z

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
       48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
       65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79])

In [102]:
a=(z%5==0)

In [103]:
a

array([False, False, False, False,  True, False, False, False, False,
        True, False, False, False, False,  True, False, False, False,
       False,  True, False, False, False, False,  True, False, False,
       False, False,  True, False, False, False, False,  True, False,
       False, False, False,  True, False, False, False, False,  True,
       False, False, False, False])

In [107]:
z[a]

array([35, 40, 45, 50, 55, 60, 65, 70, 75])

# 8. write a program to create a 2D array with 1 on the border and 0 inside.

In [108]:
x=np.ones((5,5))

In [109]:
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [110]:
x[1:-1,1:-1]=0

In [111]:
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

# 9.write a program to create a checkpoint pattern. don't use default array function checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]

# 10. write a program to find common values between two arrays.

In [134]:
y1=np.array([10,20,40,60])
y2=np.array([10,20,40,50,60])

In [137]:
print("Array1: ",y1)
print("Array2: ",y2)
print(y1&y1)

Array1:  [10 20 40 60]
Array2:  [10 20 40 50 60]
[10 20 40 60]


# 11. write a program to create an array 2d array and then reshape into 1d array

In [114]:
x=np.arange(1,11).reshape(5,2)

In [115]:
x

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [118]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# 12. write a user defined function for creating a 1 or 2d array from scratch without using array functions